### ISSUE TITLE
Ignore unused functions

### ISSUE THREAD

**Issue by rafmos** [reactway/scss-bundle#80]
Hi,

It would be nice to have an option that is going to ignore functions in imported files that are not used in the entryfile.

Example:

entry-file.scss:

```SCSS
@import "imported-file.scss
$test: my-function1();
```

imported-file.scss:
```SCSS
@function my-function1() {
  @return (
     color: red;
  );
}

@function my-function2() {
  @return (
     color: blue;
  );
}
```

The output file should look like this:
```SCSS
@function my-function1() {
  @return (
     color: red;
  );
}

$test: my-function1();
```

Instead of this:

```SCSS
@function my-function1() {
  @return (
     color: red;
  );
}

@function my-function2() {
  @return (
     color: blue;
  );
}

$test: my-function1();
```
