### ISSUE TITLE
ignoreImports option does not seem to work with ~@angular/material/theming imports.

### ISSUE THREAD

**Issue by MalumAtire832** [reactway/scss-bundle#81]
**Describe the bug**
`ignoreImports` option does not seem to work with `~@angular/material/theming` imports.

**To Reproduce**
toolbar.component-theme.scss
```scss
@import "~@angular/material/theming";

@mixin htg-toolbar-theme($theme) {

  $primary: map-get($theme, primary);

  .htg-toolbar {
    background-color: mat-color($primary);
  }
}
```

components.scss
```scss
@import "../htg-navigation/components/toolbar/toolbar.component-theme";

@mixin component-themes($theme, $company-logo) {
  @include htg-toolbar-theme($theme);
}
```

index.scss
```scss
@import "components";
```

scss-bundle.config.json
```json
{
  "bundlerOptions": {
    "entryFile": "./src/lib/scss/index.scss",
    "rootDir": "./src/lib/",
    "outFile": "dist/shared-components/bundled.scss",
    "ignoreImports": ["~@angular/.*"],
    "logLevel": "debug"
  }
}
```

**Expected behavior**
The `~@angular/material/theming` imports should be ignored and the files should be bundled.

**Package version:** v3.0.2
**Node version:** v12.13.0
**OS:** Windows 10 - 1903
